[package]
name = "hc_zome_rea_proposed_intent_index_planning"
version = "0.1.0"
authors = ["JhonatanHern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
# :DUPE: hdk-rust-revid
hdk = "=0.0.47-alpha1"
hdk_proc_macros = "=0.0.47-alpha1"

hc_zome_rea_proposed_intent_defs = { path = "../../../../../lib/rea_proposed_intent/defs" }
hc_zome_rea_proposed_intent_rpc = { path = "../../../../../lib/rea_proposed_intent/rpc" }
hc_zome_rea_proposed_intent_lib_destination_planning = { path = "../../../../../lib/rea_proposed_intent/lib_destination_planning" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
